### ISSUE TITLE
Error trying to run build

### ISSUE THREAD

**Issue by aidanreilly** [doctales/ph-schematron-ditatestfiles#1]
I get an error in Oxygen when trying to run the test cases: 

C:\Users\jreillai\Downloads\ph-schematron-ditatestfiles-master\ph-schematron-ditatestfiles-master\build.xml:25: Reference path.ph-schematron not found.
	at org.apache.tools.ant.types.Reference.getReferencedObject(Reference.java:115)
	at org.apache.tools.ant.types.DataType.dieOnCircularReference(DataType.java:144)
	at org.apache.tools.ant.types.Path.dieOnCircularReference(Path.java:493)
	at org.apache.tools.ant.types.DataType.dieOnCircularReference(DataType.java:115)
	at org.apache.tools.ant.types.DataType.getCheckedRef(DataType.java:248)
	at org.apache.tools.ant.types.DataType.getCheckedRef(DataType.java:214)
	at org.apache.tools.ant.types.DataType.getCheckedRef(DataType.java:202)
	at org.apache.tools.ant.types.Path.isFilesystemOnly(Path.java:717)
	at org.apache.tools.ant.types.resources.BaseResourceCollectionContainer.isFilesystemOnly(BaseResourceCollectionContainer.java:169)
	at org.apache.tools.ant.types.Path.assertFilesystemOnly(Path.java:731)
	at org.apache.tools.ant.types.Path.list(Path.java:376)
	at org.apache.tools.ant.types.Path.addExisting(Path.java:329)
	at org.apache.tools.ant.types.Path.addExisting(Path.java:317)
	at org.apache.tools.ant.types.Path.concatSpecialPath(Path.java:568)
	at org.apache.tools.ant.types.Path.concatSystemClasspath(Path.java:528)
	at org.apache.tools.ant.AntClassLoader.setClassPath(AntClassLoader.java:359)
	at org.apache.tools.ant.AntClassLoader.<init>(AntClassLoader.java:273)
	at org.apache.tools.ant.AntClassLoader.<init>(AntClassLoader.java:294)
	at org.apache.tools.ant.AntClassLoader.newAntClassLoader(AntClassLoader.java:1569)
	at org.apache.tools.ant.Project.createClassLoader(Project.java:344)
	at org.apache.tools.ant.util.ClasspathUtils.getUniqueClassLoaderForPath(ClasspathUtils.java:206)
	at org.apache.tools.ant.util.ClasspathUtils.getClassLoaderForPath(ClasspathUtils.java:183)
	at org.apache.tools.ant.util.ClasspathUtils$Delegate.getClassLoader(ClasspathUtils.java:411)
	at org.apache.tools.ant.taskdefs.DefBase.createLoader(DefBase.java:142)
	at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:210)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at ro.sync.exml.ant.core.project.ImplicitTarget.execute(ImplicitTarget.java:70)
	at ro.sync.exml.ant.core.project.AntProjectHelper.parseInternal(AntProjectHelper.java:221)
	at ro.sync.exml.ant.core.project.AntProjectHelper.parse(AntProjectHelper.java:111)
	at ro.sync.exml.validate.external.ant.AntValidator.validate(AntValidator.java:119)
	at ro.sync.exml.validate.b.c.b.n(Unknown Source)
	at ro.sync.exml.validate.f$1.b(Unknown Source)
	at ro.sync.exml.validate.f$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at ro.sync.util.security.f.y(Unknown Source)
	at ro.sync.exml.validate.f$2$1$1.b(Unknown Source)
	at ro.sync.exml.validate.f$2$1$1.run(Unknown Source)
	at ro.sync.util.security.f.h(Unknown Source)
	at ro.sync.exml.validate.f$2$1.b(Unknown Source)
	at ro.sync.exml.validate.f$2$1.run(Unknown Source)
	at ro.sync.util.security.f.l(Unknown Source)
	at ro.sync.exml.validate.f$2.b(Unknown Source)
	at ro.sync.exml.validate.f$2.run(Unknown Source)
	at ro.sync.util.security.f.u(Unknown Source)
	at ro.sync.exml.validate.f.d(Unknown Source)
	at ro.sync.exml.editor.validate.p.j(Unknown Source)
	at ro.sync.exml.editor.validate.p.y(Unknown Source)
	at ro.sync.exml.editor.validate.p.z(Unknown Source)
	at ro.sync.exml.editor.validate.p.g(Unknown Source)
	at ro.sync.exml.editor.kd.e(Unknown Source)
	at ro.sync.exml.editor.kd$1.pie(Unknown Source)
	at ro.sync.ui.application.nb.run(Unknown Source)

**Comment by xephon2** [comment]
@aidanreilly, I have forgotten that this repository exists and is public. I'll delete it. Please test with the org.doctales.schematron plugin directly.
